# Broadcasting in numpy

In [1]:
import numpy as np

In [3]:
A = np.array([
    [56,0,4.4,68],
    [1.2,104, 52,8.0],
    [1.8,135,99, 0.9]
])
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [6]:
cal = A.sum(axis = 0); cal

array([ 59. , 239. , 155.4,  76.9])

In [10]:
A.sum(axis = 0)

array([ 59. , 239. , 155.4,  76.9])

In [15]:
100 * A/cal.reshape(1,4)

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

Mr Ng's tips

In [34]:
a = np.random.randn(5); a

array([ 0.76158085,  0.17034945,  0.08570363, -0.74902348,  0.85448423])

In [35]:
a.shape

(5,)

In [36]:
np.dot(a, a.T)

1.9075489205230485

In [39]:
b = np.random.randn(5,1); b

array([[-1.22512476],
       [ 0.56718239],
       [ 0.26800435],
       [-1.77891504],
       [-0.0301397 ]])

In [40]:
b.shape

(5, 1)

In [41]:
np.dot(b,b.T)

array([[ 1.50093067e+00, -6.94869190e-01, -3.28338761e-01,
         2.17939285e+00,  3.69248983e-02],
       [-6.94869190e-01,  3.21695865e-01,  1.52007347e-01,
        -1.00896928e+00, -1.70947097e-02],
       [-3.28338761e-01,  1.52007347e-01,  7.18263301e-02,
        -4.76756963e-01, -8.07757185e-03],
       [ 2.17939285e+00, -1.00896928e+00, -4.76756963e-01,
         3.16453870e+00,  5.36159737e-02],
       [ 3.69248983e-02, -1.70947097e-02, -8.07757185e-03,
         5.36159737e-02,  9.08401793e-04]])

In [44]:
assert(b.shape == (5,1))

test

In [47]:
img = np.random.randn(32,32,3)
img.shape

(32, 32, 3)

In [55]:


img.reshape((img.size), 1).shape

(3072, 1)

In [59]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
(a * b).shape

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [62]:
a = np.random.randn(12288,150)
b = np.random.randn(150,45)
np.dot(a ,b).shape

(12288, 45)

In [67]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
a + b.T

array([[ 0.29564427, -0.52879544, -0.14610398],
       [-1.14907053, -1.90381968, -2.84075764],
       [-2.00858686, -0.76512049, -2.67093787],
       [-0.53470587,  0.15536059,  1.277864  ]])

In [68]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
(a*b).shape

(3, 3)