In [2]:
import numpy as np

## dot product

In [3]:
x = np.array([1,2]);x

array([1, 2])

In [4]:
A = np.array([[2,5],
              [1,3]]);A

array([[2, 5],
       [1, 3]])

In [5]:
np.dot(A,x)

array([12,  7])

In [6]:
A = np.array([[1,2,0],
              [2,0,3],
              [4,1,1]]);
b = np.array([3,-2,1])
np.dot(A,b)

array([-1,  9, 11])

## combining masks

In [39]:
a = np.zeros([4,4])
a[:2,2:4] = 1
a

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
b = np.zeros([4,4])
b[2:4,:2] = 1
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [40]:
np.maximum(a,b)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

## zeros array

In [41]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])