In [1]:
import numpy as np

## dot product

In [2]:
x = np.array([1,2]);x

array([1, 2])

In [3]:
A = np.array([[2,5],
              [1,3]]);A

array([[2, 5],
       [1, 3]])

In [4]:
np.dot(A,x)

array([12,  7])

In [5]:
A = np.array([[1,2,0],
              [2,0,3],
              [4,1,1]]);
b = np.array([3,-2,1])
np.dot(A,b)

array([-1,  9, 11])